# Generated by Django 4.2.23 on 2025-11-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "사용자 프로필", "verbose_name_plural": "사용자 프로필"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "사용자", "verbose_name_plural": "사용자"},
        ),
    ]
