# Generated by Django 4.2.23 on 2025-12-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_deleted_at_profile_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
