# Generated by Django 4.2.27 on 2026-02-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="nickname",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="닉네임"),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="프로필 이미지"
            ),
        ),
    ]
