# Generated by Django 4.2.3 on 2025-03-10 15:32

from django.db import migrations, models
from django.utils import timezone


def set_default_created_at(apps, schema_editor):
    Vote = apps.get_model("poker_face", "Vote")
    Vote.objects.filter(created_at__isnull=True).update(created_at=timezone.now())


class Migration(migrations.Migration):
    dependencies = [
        ("poker_face", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RunPython(set_default_created_at),
    ]
