# Generated by Django 4.2.3 on 2025-02-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poker_face", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="user",
            name="real_name",
            field=models.CharField(default="", max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="user_name",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
    ]
