# Generated by Django 4.2.3 on 2025-03-10 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("poker_face", "0002_auto_20250311_0032"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="deleted_at",
            field=models.DateTimeField(blank=True, help_text="삭제 일시", null=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="is_deleted",
            field=models.BooleanField(default=False, help_text="삭제 여부"),
        ),
        migrations.AddField(
            model_name="vote",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="수정 일시"),
        ),
        migrations.AlterField(
            model_name="poll",
            name="created_by",
            field=models.ForeignKey(
                help_text="투표 생성자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="생성 일시"),
        ),
        migrations.AlterField(
            model_name="vote",
            name="voted_by",
            field=models.ForeignKey(
                help_text="투표한 사용자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
