# Generated by Django 4.2.3 on 2025-03-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poker_face", "0003_vote_deleted_at_vote_is_deleted_vote_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
