version: "3.9"

services:
  nine-pjt:
    image: nine-pjt:latest
    container_name: nine-pjt
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    working_dir: /app
    volumes:
      - ./config:/app/config
      - ./apps:/app/apps
      - ./static:/app/static
      - ./templates:/app/templates
    env_file: ./.env
    platform: "linux/amd64"
    networks: nine-pjt-network

networks:
  - nine-pjt-network
