version: "3.8"

services:
  nine-pjt:
    container_name: nine-pjt
    restart: always
    volumes:
      - ./config:/app/config
      - ./apps:/app/apps
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings.deploy
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - local-net

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./templates:/app/templates
    ports:
      - "80:80"
    networks: 
      - local-net
    depends_on:
      - nine-pjt

networks:
  local-net:
    driver: bridge
