services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --reload --log-level "debug"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      PYTHONPATH: /app
    env_file: ./backend/.env
    networks:
      - local-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - frontend_build:/app/dist
    command: echo "Frontend build completed"
    networks:
      - local-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/static:/app/static
      - ./backend/templates:/app/templates
      - frontend_build:/usr/share/nginx/html  # 빌드된 프론트엔드 파일 마운트
    networks:
      - local-network
    depends_on:
      - backend
      - frontend

networks:
  local-network:
    driver: bridge

volumes:
  frontend_build:  # 빌드된 파일을 저장할 볼륨
