version: "3.8"

services:
  nine-pjt:
    image: nine-pjt:latest
    container_name: nine-pjt
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    expose:
      - "8000"
    command: bash -c "gunicorn config.wsgi -b 0.0.0.0:8000"
    working_dir: /app
    volumes:
      - ./config:/app/config
      - ./apps:/app/apps
      - ./static:/app/static
      - ./templates:/app/templates
    env_file: ./.env
    platform: "linux/amd64"
    networks:
      - nine-pjt-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
      - ./templates:/app/templates
    networks: 
      - nine-pjt-network
    depends_on:
      - nine-pjt

networks:
  nine-pjt-network:
    driver: bridge
