# Generated by Django 4.2.23 on 2025-11-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_hashtag_posthashtag"),
    ]

    operations = [
        migrations.AddField(
            model_name="hashtag",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="삭제일시"),
        ),
        migrations.AddField(
            model_name="hashtag",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="삭제 여부"),
        ),
        migrations.AddField(
            model_name="hashtag",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일시"),
        ),
        migrations.AddField(
            model_name="post",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="삭제일시"),
        ),
        migrations.AddField(
            model_name="post",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="삭제 여부"),
        ),
        migrations.AddField(
            model_name="posthashtag",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="삭제일시"),
        ),
        migrations.AddField(
            model_name="posthashtag",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="삭제 여부"),
        ),
        migrations.AddField(
            model_name="posthashtag",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일시"),
        ),
    ]
