# Generated by Django 4.2.3 on 2024-01-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="deleted_at",
        ),
        migrations.AlterField(
            model_name="link",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
