# Generated by Django 4.2.3 on 2024-01-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0002_remove_link_deleted_at_alter_link_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.URLField(max_length=1000),
        ),
    ]
