# Generated by Django 4.2.23 on 2025-10-30 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="제목")),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=18, verbose_name="금액"),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="지출 시각")),
                ("note", models.TextField(blank=True, verbose_name="비고")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("is_settled", models.BooleanField(default=False, verbose_name="정산 완료 여부")),
            ],
            options={
                "verbose_name": "지출",
                "verbose_name_plural": "지출들",
            },
        ),
        migrations.CreateModel(
            name="SettlementGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="이름")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settlement_groups",
                        to="organizations.organization",
                        verbose_name="조직",
                    ),
                ),
            ],
            options={
                "verbose_name": "정산 그룹",
                "verbose_name_plural": "정산 그룹들",
            },
        ),
        migrations.CreateModel(
            name="ExpenseAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file_path", models.CharField(max_length=255, verbose_name="파일 경로")),
                ("caption", models.CharField(blank=True, max_length=200, verbose_name="설명")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="settlements.expense",
                        verbose_name="지출",
                    ),
                ),
            ],
            options={
                "verbose_name": "지출 첨부",
                "verbose_name_plural": "지출 첨부들",
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="settlements.settlementgroup",
                verbose_name="그룹",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="payer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paid_expenses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="지불자",
            ),
        ),
    ]
