# Generated by Django 4.2.23 on 2025-11-05 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("settlements", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"verbose_name": "지출 내역", "verbose_name_plural": "지출 내역"},
        ),
        migrations.AlterModelOptions(
            name="expenseattachment",
            options={
                "verbose_name": "지출 내역 첨부 자료",
                "verbose_name_plural": "지출 내역 첨부 자료",
            },
        ),
        migrations.AlterModelOptions(
            name="settlementgroup",
            options={"verbose_name": "정산 그룹", "verbose_name_plural": "정산 그룹"},
        ),
        migrations.AlterField(
            model_name="expense",
            name="payer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paid_expenses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="지출자",
            ),
        ),
        migrations.AlterField(
            model_name="expenseattachment",
            name="expense",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="settlements.expense",
                verbose_name="지출 내역",
            ),
        ),
    ]
