# Generated by Django 4.2.23 on 2025-12-07 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements", "0004_remove_expense_note_remove_expense_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="삭제일시"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="삭제 여부")),
                (
                    "counterparty_name",
                    models.CharField(blank=True, max_length=200, verbose_name="거래처/입금자"),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=18, verbose_name="거래 금액"),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        help_text="예: KRW, USD. 비어 있으면 기본 통화를 의미.",
                        max_length=8,
                        verbose_name="통화 코드",
                    ),
                ),
                (
                    "transacted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="거래 일시"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        blank=True,
                        choices=[("DEPOSIT", "입금"), ("WITHDRAWAL", "출금")],
                        help_text="DEPOSIT: 입금, WITHDRAWAL: 출금",
                        max_length=16,
                        verbose_name="거래 유형",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="거래 후 잔액",
                    ),
                ),
                (
                    "memo",
                    models.TextField(
                        blank=True,
                        help_text="거래 적요, 메모 등 추가 정보",
                        verbose_name="적요/메모",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="settlements.settlementgroup",
                        verbose_name="그룹",
                    ),
                ),
            ],
            options={
                "verbose_name": "거래 내역",
                "verbose_name_plural": "거래 내역",
            },
        ),
        migrations.CreateModel(
            name="TransactionAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="삭제일시"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="삭제 여부")),
                ("file_path", models.CharField(max_length=255, verbose_name="파일 경로")),
                ("caption", models.CharField(blank=True, max_length=200, verbose_name="설명")),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="settlements.transaction",
                        verbose_name="거래 내역",
                    ),
                ),
            ],
            options={
                "verbose_name": "거래 내역 첨부 자료",
                "verbose_name_plural": "거래 내역 첨부 자료",
            },
        ),
    ]
