# Generated by Django 4.2.23 on 2025-11-05 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0004_alter_organization_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="앨범명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화 여부")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="organizations.organization",
                        verbose_name="조직",
                    ),
                ),
            ],
            options={
                "verbose_name": "앨범",
                "verbose_name_plural": "앨범",
            },
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file_path", models.CharField(max_length=255, verbose_name="파일 경로")),
                ("caption", models.TextField(blank=True, verbose_name="설명")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pictures",
                        to="pictures.album",
                        verbose_name="앨범",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="organizations.organization",
                        verbose_name="조직",
                    ),
                ),
            ],
            options={
                "verbose_name": "사진",
                "verbose_name_plural": "사진",
            },
        ),
    ]
