# Generated by Django 4.2.23 on 2025-10-29 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="조직 또는 모임의 이름", max_length=100, verbose_name="조직명"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="조직에 대한 상세 설명", verbose_name="설명"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화 여부")),
            ],
            options={
                "verbose_name": "조직",
                "verbose_name_plural": "조직들",
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True, verbose_name="가입일")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성 멤버십 여부")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organizations.organization",
                        verbose_name="조직",
                    ),
                ),
            ],
            options={
                "verbose_name": "조직 멤버십",
                "verbose_name_plural": "조직 멤버십들",
            },
        ),
    ]
