# Generated by Django 4.2.23 on 2025-11-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_organizationmembership_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={"verbose_name": "조직", "verbose_name_plural": "조직"},
        ),
        migrations.AlterModelOptions(
            name="organizationmembership",
            options={"verbose_name": "조직 멤버", "verbose_name_plural": "조직 멤버"},
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="활성 멤버 여부"),
        ),
    ]
