# Generated by Django 4.2.3 on 2024-01-11 09:13

import apps.albums.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("origin", models.ImageField(upload_to=apps.albums.models.origin_path)),
            ],
        ),
    ]
