# Generated by Django 4.2.3 on 2024-01-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
