# Generated by Django 4.2.23 on 2025-12-01 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements", "0003_expense_deleted_at_expense_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="note",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="title",
        ),
        migrations.AddField(
            model_name="expense",
            name="currency",
            field=models.CharField(
                blank=True,
                help_text="예: KRW, USD. 비어 있으면 기본 통화를 의미.",
                max_length=8,
                verbose_name="통화 코드",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="memo",
            field=models.TextField(
                blank=True,
                help_text="추가로 유의미한 정보(카드사명, 승인번호 등)",
                verbose_name="메모",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="merchant_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="결제처/가맹점명"),
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_method",
            field=models.CharField(
                blank=True,
                help_text="예: CREDIT_CARD, CASH, TRANSFER 등",
                max_length=32,
                verbose_name="결제 수단",
            ),
        ),
        migrations.CreateModel(
            name="ExpenseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="삭제일시"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="삭제 여부")),
                ("name", models.CharField(blank=True, max_length=200, verbose_name="품목명")),
                (
                    "quantity",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="수량"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True, verbose_name="단가"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="합계 금액",
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="settlements.expense",
                        verbose_name="지출 내역",
                    ),
                ),
            ],
            options={
                "verbose_name": "지출 품목",
                "verbose_name_plural": "지출 품목",
            },
        ),
    ]
