# Generated by Django 4.2.27 on 2026-02-25 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("settlements", "0005_transaction_transactionattachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="삭제일시"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="삭제 여부")),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, max_digits=18, verbose_name="총 금액"),
                ),
                ("member_count", models.PositiveIntegerField(verbose_name="참여 인원")),
                ("confirmed_at", models.DateTimeField(auto_now_add=True, verbose_name="확정 일시")),
                ("memo", models.TextField(blank=True, verbose_name="메모")),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_settlements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="확정자",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="settlements.settlementgroup",
                        verbose_name="정산 그룹",
                    ),
                ),
            ],
            options={
                "verbose_name": "정산 확정",
                "verbose_name_plural": "정산 확정",
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="split_type",
            field=models.CharField(
                choices=[("EQUAL", "균등분할"), ("CUSTOM", "직접지정")],
                default="EQUAL",
                max_length=16,
                verbose_name="분할 방식",
            ),
        ),
        migrations.CreateModel(
            name="SettlementTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="삭제일시"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="삭제 여부")),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=18, verbose_name="송금 금액"),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="송금 완료 여부")),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="송금 완료 일시"),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_transfers_from",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="보내는 사람",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="settlements.settlement",
                        verbose_name="정산",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_transfers_to",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="받는 사람",
                    ),
                ),
            ],
            options={
                "verbose_name": "정산 송금",
                "verbose_name_plural": "정산 송금",
            },
        ),
        migrations.CreateModel(
            name="SettlementExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="삭제일시"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="삭제 여부")),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_records",
                        to="settlements.expense",
                        verbose_name="지출 내역",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_expenses",
                        to="settlements.settlement",
                        verbose_name="정산",
                    ),
                ),
            ],
            options={
                "verbose_name": "정산 포함 지출",
                "verbose_name_plural": "정산 포함 지출",
                "unique_together": {("settlement", "expense")},
            },
        ),
        migrations.CreateModel(
            name="ExpenseShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="삭제일시"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="삭제 여부")),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="EQUAL이면 null(자동 계산), CUSTOM이면 직접 지정",
                        max_digits=18,
                        null=True,
                        verbose_name="분담 금액",
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="settlements.expense",
                        verbose_name="지출 내역",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_shares",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="분담자",
                    ),
                ),
            ],
            options={
                "verbose_name": "지출 분담",
                "verbose_name_plural": "지출 분담",
                "unique_together": {("expense", "user")},
            },
        ),
    ]
