# Generated by Django 4.2.23 on 2025-10-30 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("organizations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmembership",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                help_text="해당 조직에서 사용하는 사용자 프로필",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organization_memberships",
                to="users.profile",
                verbose_name="사용자 프로필",
            ),
        ),
    ]
