# Generated by Django 4.2.23 on 2025-11-30 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_alter_organization_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationmembership",
            name="joined_at",
        ),
        migrations.AddField(
            model_name="organization",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="삭제일시"),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="삭제 여부"),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="생성일시"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="삭제일시"),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="삭제 여부"),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일시"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일시"),
        ),
    ]
