# Generated by Django 4.2.27 on 2026-02-04 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.organizations.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0005_remove_organizationmembership_joined_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('code', models.CharField(default=apps.organizations.models.generate_invitation_code, max_length=8, unique=True, verbose_name='초대 코드')),
                ('expires_at', models.DateTimeField(help_text='초대 코드 만료 시간', verbose_name='만료일')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = 무제한', verbose_name='최대 사용 횟수')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='사용 횟수')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invitations', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.organization', verbose_name='조직')),
            ],
            options={
                'verbose_name': '조직 초대',
                'verbose_name_plural': '조직 초대',
            },
        ),
    ]
